[versions]
kotlin = "1.8.21"
coroutines = "1.8.21"
dokka = "1.8.20"
kotest = "5.6.2"
spotless = "6.20.0"
mavenNexus = "1.3.0"
ktlint = "0.48.2"
nodejsPlugin = "6.0.0"
androidPlugin = "8.1.0"
nodejs = "16.14.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotest-multiplatform = { id = "io.kotest.multiplatform", version.ref = "kotest" }
android-library = { id = "com.android.library", version.ref = "androidPlugin" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "mavenNexus" }
nodejs = { id = "com.github.node-gradle.node", version.ref = "nodejsPlugin" }
